// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3gryPqgO-Ubb6mmu7lLvfQWj7PVC68RU',
    appId: '1:21407899216:web:18e60efe524781d9f03b55',
    messagingSenderId: '21407899216',
    projectId: 'portfolio-14472',
    authDomain: 'portfolio-14472.firebaseapp.com',
    storageBucket: 'portfolio-14472.firebasestorage.app',
    measurementId: 'G-C4E2TLWT4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLIt_48xbsdCGpPc4ToXbb2KB8S1yXxkk',
    appId: '1:21407899216:android:421cc398baf2ecfbf03b55',
    messagingSenderId: '21407899216',
    projectId: 'portfolio-14472',
    storageBucket: 'portfolio-14472.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKjWrefMyet6I9RyxfYIg87A6LMUHTs_A',
    appId: '1:21407899216:ios:243f03f26c84bba7f03b55',
    messagingSenderId: '21407899216',
    projectId: 'portfolio-14472',
    storageBucket: 'portfolio-14472.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKjWrefMyet6I9RyxfYIg87A6LMUHTs_A',
    appId: '1:21407899216:ios:243f03f26c84bba7f03b55',
    messagingSenderId: '21407899216',
    projectId: 'portfolio-14472',
    storageBucket: 'portfolio-14472.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3gryPqgO-Ubb6mmu7lLvfQWj7PVC68RU',
    appId: '1:21407899216:web:73353e913ea789a1f03b55',
    messagingSenderId: '21407899216',
    projectId: 'portfolio-14472',
    authDomain: 'portfolio-14472.firebaseapp.com',
    storageBucket: 'portfolio-14472.firebasestorage.app',
    measurementId: 'G-BT24J38JKD',
  );
}
